<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Types.fs" />
    <Compile Include="Label.fs" />
  </ItemGroup>

  <PropertyGroup>
    <PackageId>Fabra</PackageId>
    <Version>0.0.3</Version>
    <Title>Fabra</Title>
    <Authors>Rob Slavin</Authors>
    <Company>Rob Slavin</Company>
    <Description>An F# DSL for generating Zebra Programming Language (ZPL) labels.</Description>
    <PackageTags>fsharp;ZPL;zebra;label;barcode</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/auslavs/Fabra</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/auslavs/Fabra</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
